sudo: required
services:
  - docker

language: go
go: 1.10.x
go_import_path: github.com/mattnolf/sarumhymnal

before-install: 
  - docker build -t mattnolf/sarumhymnal .
script:
- go test -v ./...
notifications:
  slack:
    rooms:
      - secure: kwe211Lv9vDSrfC6Nilso0rinrm5QV6dN6j67aETKQz5/Y9sixFV3KHwNi8r4V8GmTY7DBGfH+S78hdzv6i78pHfxHeQkYHRIFX7iaFpVT76L24PbXjU4iv+0QliGcoqjmigsWFxKgbnrO+6rBPFjDeKn3YeD36M8jqxLW21gZbEjhx79UqvTnkmW2Pduja4f4MHDTvWpo7HeEgV6T4qqszQdSkePGvStKdoYxcClhT3G1WAVgnAtR9PticxZfbO3/THyxSnmjeHRojXZC8Ft+YDKcr3ezkv1DEGnXteatbCsBl9ARk6t3OB67wVB3uM+RuA73ST0UIi4ryWu3GangzZDf2oc+q/5Fx5Q36OVVjRw5Bj0LVDBSk4HsXw1dDsREFRpg6kAACNUEqvdZq0alKDRJ7JIQbNzlUrU9LMDtg9jxJnXuk35ElkQ1S6BqFl/X86TPx8/vq6Tvu0FUD94UfAA0LZBXwFnhSVPxEyVRIib+bSFxPcRTcJH7ZZE8Rs1klOAak/Dn+GLtAiVQkSjgV22+5guM0hZ/GLFoJQHZ7J+j/tBGUD2B4wayLKzGqbSH2lF6uCFZZPBXnw4EuQBfkE7u681NeWDNEauS9Q041WhSt1PlIS9WbpyGP5jk/Fn21AiHCHGJ5tHWTl/x2JDBxAfUmjrxGDYlJgO3tOlXE=
    on_success: always
    on_failure: always