version: "3"
services:
  cantaloupe:
    image: atnu-cantaloupe
    build:
      context: ./
      dockerfile: services/cantaloupe/Dockerfile
    ports:
      - "2400:8182"
    environment:
      - "AWS_DEFAULT_REGION=eu-west-1"
    networks:
      - sarum-hymnal
  postgres:
    image: atnu-db
    build:
      context: ./
      dockerfile: services/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PnvaG9LhCb8DXPbp
    ports:
     - "2300:5432"
    networks:
      - sarum-hymnal
  adminer:
    image: adminer
    restart: always
    ports:
      - "2600:8080"
    networks:
      - sarum-hymnal
  client:
    image: atnu/sarum-client
    build:
      context: ./
      dockerfile: services/client/Dockerfile
    ports:
      - "2100:80"
    networks:
      - sarum-hymnal
  server:
    image: atnu-webserver
    build:
      context: ./
      dockerfile: services/server/Dockerfile
    ports:
      - "2200:4100"
    networks:
      - sarum-hymnal

networks:
  sarum-hymnal:
