version: "3"
services:
  cantaloupe:
    image: atnu-cantaloupe
    build:
      context: ./
      dockerfile: services/cantaloupe/Dockerfile
    ports:
      - "8182:8182"
    environment:
      - "AWS_DEFAULT_REGION=eu-west-1"
    networks:
      - public
  minio:
    image: minio/minio
    ports:
     - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio-1234"
    networks:
     - public
    volumes:
     - ./data/minio:/data
    command: server /data
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_example
    networks:
      - public
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - public
  create-minio-buckets:
    image: alpine
    volumes:
     - ./data/minio:/data/
    command: ["sh", "-c", "[ -d /data/atnu-images ] || mkdir -p /data/atnu-images"]
  client:
    image: node:8
    volumes:
      - "./services/client/:/usr/local/app"
    command: "tail -f /dev/null"
    ports:
      - "4200:4200"
    networks:
      - public

networks:
  public:
